"""Build from scratch under two hash seeds and compare every generated byte."""

import hashlib
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def manifest():
    paths = sorted((ROOT / "dist").rglob("*")) + [ROOT / "backend/event-ids.mjs"]
    return {
        str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in paths
        if path.is_file()
    }


def main():
    previous = None
    for seed in ("1", "73"):
        subprocess.run(
            [sys.executable, str(ROOT / "scripts/build.py")],
            env={**os.environ, "PYTHONHASHSEED": seed},
            check=True,
        )
        current = manifest()
        if previous is not None and current != previous:
            changed = sorted(
                key
                for key in current.keys() | previous.keys()
                if current.get(key) != previous.get(key)
            )
            raise AssertionError(f"Non-reproducible artifacts: {changed}")
        previous = current
        if seed == "1":
            (ROOT / "dist/stale-build-artifact.txt").write_text(
                "Must not survive a rebuild", encoding="utf-8"
            )
    print(f"PASS: {len(previous)} artifacts are identical across clean builds and hash seeds")


if __name__ == "__main__":
    main()
